config/routes.rb
Rails.application.routes.draw do
  root "sessions#home"

  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  delete 'logout', to: 'sessions#destroy'

  get 'auth/google_oauth2/callback', to: 'sessions#omniauth'

  resources :users do
    resources :statuses, shallow: true
  end
  resources :parties do
    resources :messages, shallow: true
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/party.rb
class Party < ApplicationRecord
  has_many :user_parties
  has_many :users, through: :user_parties
  has_many :messages
  
  validates :name, { presence: true }
  
  scope :one_on_one, -> { where("users.count == 2") }
  
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  before_action :set_party, only: %i[ show edit update destroy ]
  
  def index
    @party = Party.all
  end

  def new
    @party = Party.new
  end

  def create
    @party = Party.new(party_params)
    current_user.parties << @party
    if @party.save
      render :index
    else
      render :new
    end
  end

  def show
    @party.build_message(user: current_user)
  end

  def edit
  end

  def update
    if @party.update(party_params)
      redirect_to @party
    else
      render :edit
    end
  end

  def destroy
    if @party.destroy
      redirect_to parties_path, notice: "Party deleted"
    else
      redirect_to parties_path, notice: "Party not found"
    end
  end

  private
  
  def set_party
    @party = Party.find_by_id(params[:id])
  end
  
  def party_params
    params.require(:party).permit(
      :name,
      user_ids: [],
      message_ids: []
    )
  end

end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/parties/_form.html.erb
<%= form_for @party do |f| %>
  <%= f.label :name, "Party Name" %><br>
  <%= f.text_field :name %><br>

  <h3>Invite Some Friends!</h3>
  <%= f.collection_check_boxes(:user_ids, User.everyone_else(current_user), :id, :first_name) do |b| %>
      <div class="simpleWindow">
        <%= b.label class:"checkbox" do %>
         <%= b.check_box + b.text %>
        <%end%>
      </div>
    <% end %><br>
  <%= f.submit class:"green button" %>
<% end %>

app/views/parties/edit.html.erb
<% if @party.errors.any? %>
  <div class="errorWindow">
    <h2><%= pluralize(@party.errors.count, "error") %> prohibited this user from being saved:</h2>
    <% @party.errors.each do |error| %>
      <p><%= error.full_message %></p>
    <% end %>
  </div>
<% end %>

<div class="simpleWindow">
  <h1>🛠 Edit Party 🛠</h1>
  <%= render "form" %>
</div>

app/views/parties/index.html.erb
<% if current_user.parties.count != 0 %>
  <% current_user.parties.each do |party| %>
    <div class="simpleWindow">
      <h2>🎉 <%= link_to party.name.upcase, party %> 🎉</h2>
      <h4><%= party.messages.count %> Messages</h4>
      <h3>Party Goers:</h3>
      <% party.users.each do |user| %>
        <%= user.full_name %><br>
      <% end %><br>
      <div class="flex-container">
        <%= link_to "Edit Party", edit_party_path(party), class:"orange button" %>
        <%= button_to "Delete Party", party, method: :delete, data: { confirm: "Are you sure?" }, class:"red button" %>
      </div>
    </div>
  <% end %>
<% else %>
  <div class="simpleWindow">
    <h4>You have no parties! Let's start one!</h4>
    <div class="flex-container">
      <%= link_to "New Party", new_party_path, class:"blue button" %>
    </div>
  </div>
<% end %>

app/views/parties/new.html.erb
<% if @party.errors.any? %>
  <div class="errorWindow">
    <h2><%= pluralize(@party.errors.count, "error") %> prohibited this user from being saved:</h2>
    <% @party.errors.each do |error| %>
      <p><%= error.full_message %></p>
    <% end %>
  </div>
<% end %>

<div class="simpleWindow">
  <h1>🎉 New Party 🎉</h1>
  <%= render "form" %>
</div>

app/views/parties/show.html.erb
<div class="simpleWindow">
  <h2>🎉 <%= @party.name %> 🎉</h1>
</div>

<% if @party.messages.count > 0 %>
  <% @party.messages.each do |message| %>
    <div class="simpleWindow">
      <%= ago(message) %><br>
      <%= User.find_by_id(message.sender).full_name %><br><br>
      <div class="status-bubble">
        <%= message.content %>
      </div>
    </div>
  <% end %>
<% end %>

<div class="simpleWindow">
  <%= render partial: "messages/form", party:@party %>
</div>