config/routes.rb
Rails.application.routes.draw do
  root "sessions#home"

  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  delete 'logout', to: 'sessions#destroy'

  get 'auth/google_oauth2/callback', to: 'sessions#omniauth'

  resources :users do
    resources :statuses, shallow: true
  end
  resources :parties do
    resources :messages, shallow: true
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :party
  belongs_to :sender, :class_name => "User"

  validates :content, { presence: true }

  scope :urgent, -> { where("urgent = true") }
  scope :today, -> { where(updated_at: 24.hours.ago..Time.now) }
  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]
  before_action :set_party, only: %i[ index new create ]

  def index
    @messages = Message.all
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    @message.party = @party
    @message.sender = current_user
    if @message.save
      redirect_to party_path(@party)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @message.update(message_params)
      redirect_to @party
    else
      render :edit
    end
  end

  def destroy
    if @message.destroy
      redirect_to @party, success: "Message deleted"
    else
      redirect_to @party, error: "Message not found"
    end
  end

  private

  def set_message
    @message = Message.find_by_id(params[:id])
  end

  def message_params
    params.require(:message).permit(
      :party_id,
      :content,
      :urgent,
      :sender
    )
  end

  def set_party
    @party = Party.find(params[:party_id])
  end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_with(model: [@party,@message], local: true) do |f| %>
  <%= f.label :content, "Send a message!" %><br>
  <%= f.text_field :content %><br>

  <%= f.label :urgent, "Urgent?" %><br>
  <%= f.select :urgent, [['Important!', true], ['Chill', 'false']] %><br><br>

  <%= f.submit class:"green button" %>
<% end %>

app/views/messages/edit.html.erb
<div class="simpleWindow">
  <h1>🛠 Edit Message 🛠</h1>
  <%= render "form" %>
</div>

app/views/messages/index.html.erb
<h1>All Messages</h1>
<% @messages.each do |message| %>
  <div>
    <%= link_to message.content, message_path(message) %>
  </div>
<% end %>

app/views/messages/new.html.erb
<div class="simpleWindow">
  <h1>💬 New Message 💬</h1>
  <%= render "form" %>
</div>

app/views/messages/show.html.erb
<div class="simpleWindow">
</div>