config/routes.rb
Rails.application.routes.draw do
  root "sessions#home"

  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  delete 'logout', to: 'sessions#destroy'

  get 'auth/google_oauth2/callback', to: 'sessions#omniauth'

  resources :users do
    resources :statuses, shallow: true
  end
  resources :parties do
    resources :messages, shallow: true
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: %i[ edit update destroy ]
  before_action :set_user, only: %i[ index new create  ]
  
  def index
    @statuses = Status.all
  end

  def new
    @status = Status.new
  end

  def create
    @status = @user.build_status(status_params)
    if @status.save
      redirect_to @user
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @status.update(status_params)
      redirect_to user_statuses_path(@user)
    else
      render :edit
    end
  end

  def destroy
    if @status.destroy
      redirect_to user_statuses_path(@user), success: "Status deleted"
    else
      redirect_to user_statuses_path(@user), error: "Status not found"
    end
  end

  private

  def set_status
    @status = Status.find_by_id(params[:id])
  end

  def status_params
    params.require(:status).permit(
      :user_id,
      :content
    )
  end

  def set_user
    @user = User.find_by_id(params[:user_id])
  end
end

app/helpers/statuses_helper.rb
module StatusesHelper

  def ago(status)
    time_ago_in_words(status.updated_at)
  end

end

app/views/statuses/_form.html.erb
<%= form_with(model: [@user,@status], local: true) do |f| %>
  <%= f.label :content, "What do you want to say?" %><br>
  <%= f.text_field :content %><br>
  
  <%= f.submit class:"green button" %>
<% end %>

app/views/statuses/edit.html.erb
<% if @status.errors.any? %>
  <div class="errorWindow">
    <h2><%= pluralize(@status.errors.count, "error") %> prohibited this user from being saved:</h2>
    <% @status.errors.each do |error| %>
      <p><%= error.full_message %></p>
    <% end %>
  </div>
<% end %>

<div class="simpleWindow">
  <h1>🛠 Edit Status 🛠</h1>
  <%= render "form" %>
</div>

app/views/statuses/index.html.erb
<% if @statuses.count != 0 %>
  <div class="simpleWindow">
    <h1>👤 <%= current_user.full_name %> 👤</h1>
    <h3><%= @statuses.count %> Update(s)</h3>
  </div>
  <% @statuses.each do |status| %>
    <div class="simpleWindow">
      <h2>💭 <%= status.content %></h2>
      <p><i><%= ago(status) %></i><p>
      <div class="flex-container">
        <%= link_to 'Edit Status', edit_user_status_path(current_user, status), class:"orange button" %><br>
        <%= button_to 'Delete Status', user_status_path(current_user, status), method: :delete, data: { confirm: "Are you sure?" }, class:"red button" %>
      </div>
    </div>
  <% end %>
<% else %>
  <div class="simpleWindow">
    <h4>No Statuses... yet!</h4>
    <% if current_user.id == params[:id] %>
      <div class="flex container">
        <%= link_to "New Status", new_user_status_path(current_user), class:"green button" %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/statuses/new.html.erb
<% if @status.errors.any? %>
  <div class="errorWindow">
    <h2><%= pluralize(@status.errors.count, "error") %> prohibited this user from being saved:</h2>
    <% @status.errors.each do |error| %>
      <p><%= error.full_message %></p>
    <% end %>
  </div>
<% end %>

<div class="simpleWindow">
  <h1>💬 New Status 💬</h1>
  <%= render "form" %><br>
</div>