config/routes.rb
Rails.application.routes.draw do
  root "sessions#home"

  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  delete 'logout', to: 'sessions#destroy'

  get 'auth/google_oauth2/callback', to: 'sessions#omniauth'

  resources :users do
    resources :statuses, shallow: true
  end
  resources :parties do
    resources :messages, shallow: true
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :friendships
  has_many :friends, through: :friendships
  has_many :user_parties
  has_many :users, through: :user_parties
  has_many :messages
  has_many :statuses
  accepts_nested_attributes_for :statuses
  
  has_secure_password

  validates :email, {
    uniqueness: true,
    format: {  
      with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i  
    }
  }

  scope :order_by_last_name, -> { order(last_name: :asc) }
  scope :everyone_else, ->(user) { where.not("id = ?", user.id) }

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def self.create_from_omniauth(auth)
    self.find_or_create_by(uid: auth[:uid], provider: auth[:provider]) do |u|
      u.first_name = auth[:info][:first_name]
      u.last_name = auth[:info][:last_name]
      u.email = auth[:info][:email]
      u.password = SecureRandom.hex(16)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  skip_before_action :require_login, only: %i[ new create ]
  
  def index
    @users = User.all
  end

  def new
    @user = User.new
    @user.build_status
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, success: "User successfully created!"
    else
      flash.now[:error] = @user.errors.full_messages.to_sentence
      render :new
    end
  end

  def show
    @user.build_status
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to root_path
    else
      redirect_to @user
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :email,
      :password,
      :password_confirmation,
      statuses_attributes: [
        :user_id,
        :content
      ]
    )
  end

  def set_user
    @user = User.find_by_id(params[:id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div class="errorWindow">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
    <% @user.errors.each do |error| %>
      <p><%= error.full_message %></p>
    <% end %>
  </div>
<% end %>

<div class="simpleWindow">
  <h1>🛠 Edit Your Account 🛠</h1>
  <%= form_with(model: @user) do |f| %>
  <%= f.label :first_name, "👤 First Name:" %><br>
  <%= f.text_field :first_name %><br>

  <%= f.label :last_name, "👤 Last Name:" %><br>
  <%= f.text_field :last_name %><br>

  <%= f.label :email, "📧 Email:" %><br>
  <%= f.email_field :email %><br>

  <%= f.label :password, "🔑 Password:" %><br>
  <%= f.password_field :password %><br>

  <%= f.label :password_confirmation, "🔑 Confirm Password:" %><br>
  <%= f.password_field :password_confirmation %><br>
  <%= f.submit class: "blue button" %>
<% end %>
</div>

app/views/users/index.html.erb
<div class="simpleWindow">
  <h1>All Users</h1>
  <% @users.each do |user| %>
    <div class="userCard">
      <p>👤</p>
      <%= link_to user.full_name, user_statuses_path(user) %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div class="errorWindow">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
    <% @user.errors.each do |error| %>
      <p><%= error.full_message %></p>
    <% end %>
  </div>
<% end %>

<div class="simpleWindow">
  <h1>🎉 Join the Party! 🎉</h1>
  <%= form_with(model: @user) do |f| %>
    <%= f.label :first_name, "👤 First Name:" %><br>
    <%= f.text_field :first_name %><br>

    <%= f.label :last_name, "👤 Last Name:" %><br>
    <%= f.text_field :last_name %><br>

    <%= f.label :email, "📧 Email:" %><br>
    <%= f.email_field :email %><br>

    <%= f.label :password, "🔑 Password:" %><br>
    <%= f.password_field :password %><br>

    <%= f.label :password_confirmation, "🔑 Confirm Password:" %><br>
    <%= f.password_field :password_confirmation %><br>
    <%= f.fields_for :statuses do |status_form| %>
      <%= status_form.label :content, "💬 First Status Update:" %><br>
      <p>Status messages are a way to tell your fellow party-goers<br>how you're doing or if you're available to chat.<p>
      <p><i>(Max of 281 characters, beat that Twitter!)</i></p>
      <%= status_form.text_area :content, maxlength: 281 %><br>
    <% end %>
    <div class="flex-container">
      <%= f.submit class: "blue button" %>
      <%= link_to "Login", login_path, class:"orange button" %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="simpleWindow">
  <h1><%= @user.full_name %></h1>
  <% if !@user.statuses.empty? %>
    <div class="status-bubble">
      <%= @user.statuses.last.content %>
    </div>
    <%= ago(@user.statuses.last) %> ago<br><br>
  <% end %>
  <%= render partial: "statuses/form", user:@user %>
</div>

<div class="simpleWindow">
  <h3>❗️Urgent Messages❗️</h3>
  <% @user.messages.where("urgent = true").each do |message| %>
    <div class="simpleWindow">
      <%= link_to "🔎", party_path(message.party) %> <%= message.content %> - <%= User.find_by_id(message.sender).full_name %>
    </div>
  <% end %>

</div>

<div class="simpleWindow">
  <div class="flex-container">
    <%= link_to "New Party", new_party_path, class:"blue button" %>
    <%= link_to "Edit User", edit_user_path(@user), class:"orange button" %>
    <%= button_to "Delete User", @user, method: :delete, data: { confirm: "Are you sure?" }, class:"red button" %>
  </div>
</div>